platform :ios, '6.0' 
pod 'SHObjectUserInfo', :git => "https://github.com/seivan/SHObjectUserInfo"
pod 'SHSegueBlocks', :path => '../'


target :ExampleTests do
  pod 'SHTestCaseAdditions', :git => "https://github.com/seivan/SHTestCaseAdditions"
  pod 'SHFastEnumerationProtocols', :git => "https://github.com/PodFactory/SHFastEnumerationProtocols"
  pod "KIF-next"
end